version: "3.8"
services:
  backend:
    image: dioben/tqs-provider-server
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - /logistics-db-data:/var/lib/mysql  
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD= mysqlpassword
      - MYSQL_DATABASE= delivery_service
