version: "3.8"
services:
  backendmain:
    build: .
    #image: dioben/tqs-provider-server:dev
    ports:
      - 8080:8080
    depends_on:
      db_main:
        condition: service_healthy

  db_main:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -h localhost -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - ./logistics-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  default:
    name: global_network
