package logisticsmarshall.tqs.ua.controllers;// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import logisticsmarshall.tqs.ua.model.Delivery;
import logisticsmarshall.tqs.ua.model.User;
import logisticsmarshall.tqs.ua.services.DeliveryService;
import logisticsmarshall.tqs.ua.services.UserServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.MatcherAssert.*;

import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import logisticsmarshall.tqs.ua.repository.UserRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.web.server.LocalServerPort;

import java.sql.Timestamp;
import java.time.LocalDateTime;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ExtendWith(SeleniumJupiter.class)
public class MainCompanyIT {

    @LocalServerPort
    int serverPort;

    String url;

    @Autowired
    UserServiceImpl userService;

    @Autowired
    UserRepository userRepository;

    @Autowired
    DeliveryService deliveryService;

    @BeforeEach
    public void setUp() {
        url = String.format("http://backendmain:%d/", serverPort);

        User user = userRepository.findByName("marchingfood");
        Delivery del = new Delivery();
        del.setCompany(user.getCompany());
        del.setStage(Delivery.Stage.REQUESTED);
        del.setAddress("IT Test Delivery");
        del.setPickupAddress(user.getCompany().getAddress());
        del.setOrderTimestamp(Timestamp.valueOf(LocalDateTime.now()));
        del.setPriority(Delivery.Priority.HIGHPRIORITY);
        deliveryService.postDelivery(del);
    }

    @Test
    public void mainCompanyIntegration(ChromeDriver driver) {
        driver.get(url + "login");
        driver.manage().window().setSize(new Dimension(1456, 876));
        driver.findElement(By.id("password")).sendKeys("marchingfood");
        driver.findElement(By.id("username")).sendKeys("marchingfood");
        driver.findElement(By.id("login-submit")).click();
        assertThat(driver.findElement(By.xpath("(//tr/td[4])[last()]")).getText(), is("IT Test Delivery"));
        driver.findElement(By.xpath("(//button)[last()]")).click();
        driver.findElement(By.linkText("Profile")).click();
        driver.findElement(By.id("newPassword")).sendKeys("newpass");
        driver.findElement(By.id("password")).sendKeys("marchingfood");
        driver.findElement(By.cssSelector(".col-3 > .button")).click();
        driver.findElement(By.id("username")).sendKeys("marchingfood");
        driver.findElement(By.id("password")).sendKeys("newpass");
        driver.findElement(By.id("login-submit")).click();
        driver.findElement(By.linkText("LogisticsMarshall")).click();
        driver.findElement(By.cssSelector("h2")).click();
        assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Welcome to Logistics Marshall"));
        driver.findElement(By.linkText("Dashboard")).click();
        {
            WebElement element = driver.findElement(By.linkText("Dashboard"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.linkText("Profile")).click();
        driver.findElement(By.id("password")).sendKeys("newpass");
        driver.findElement(By.id("newPassword")).sendKeys("marchingfood");
        driver.findElement(By.cssSelector(".col-3 > .button")).click();
    }
}
