package logisticsmarshall.tqs.ua.controllers;// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.web.server.LocalServerPort;

import java.util.*;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ExtendWith(SeleniumJupiter.class)
public class MainRegisterDriverIT {

  @LocalServerPort
  int serverPort;

  String url;

  @BeforeEach
  public void setUp() {
    url = String.format("http://backendmain:%d/", serverPort);
  }

  @Test
  public void mainRegisterDriverIntegration(ChromeDriver driver) {
    String clientName = UUID.randomUUID().toString();
    String clientEmail = clientName+"@email.com";
    String clientPass = "randompass";

    driver.get(url + "login");
    driver.manage().window().setSize(new Dimension(1456, 876));
    driver.findElement(By.cssSelector("span > a")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys(clientName);
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.name("email")).sendKeys(clientEmail);
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.name("password")).sendKeys(clientPass);
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#div2 > h3")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#div2 > h3"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.name("phoneNo")).click();
    driver.findElement(By.name("phoneNo")).sendKeys("9123456789");
    driver.findElement(By.name("vehicle")).click();
    {
      WebElement dropdown = driver.findElement(By.name("vehicle"));
      dropdown.findElement(By.xpath("//option[. = 'Motorcycle']")).click();
    }
    driver.findElement(By.name("vehicle")).click();
    driver.findElement(By.cssSelector(".alt")).click();
    driver.findElement(By.id("username")).sendKeys(clientName);
    driver.findElement(By.id("password")).sendKeys(clientPass);
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("Log Out")).click();
  }
}
