package logisticsmarshall.tqs.ua.controllers;// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;



@SpringBootTest
@ExtendWith(SeleniumJupiter.class)
public class MainRegisterDriverIntegrationTest {
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
  }
  @AfterEach
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void mainRegisterDriverIntegration(HtmlUnitDriver driver) {
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(1456, 876));
    driver.findElement(By.cssSelector("span > a")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("gooddriver");
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.name("email")).sendKeys("gooddriver@mail.com");
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.name("password")).sendKeys("gooddriver");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#div2 > h3")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#div2 > h3"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.name("phoneNo")).click();
    driver.findElement(By.name("phoneNo")).sendKeys("9123456789");
    driver.findElement(By.name("vehicle")).click();
    {
      WebElement dropdown = driver.findElement(By.name("vehicle"));
      dropdown.findElement(By.xpath("//option[. = 'Motorcycle']")).click();
    }
    driver.findElement(By.name("vehicle")).click();
    driver.findElement(By.cssSelector(".alt")).click();
  }
}
