package logisticsmarshall.tqs.ua.controllers;// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import logisticsmarshall.tqs.ua.model.User;
import logisticsmarshall.tqs.ua.repository.DeliveryRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import logisticsmarshall.tqs.ua.model.Delivery;
import logisticsmarshall.tqs.ua.repository.UserRepository;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@ExtendWith(SeleniumJupiter.class)
public class MainCompanyIntegrationTest {


  @Autowired
  UserRepository userRepository;

  @Autowired
  DeliveryRepository deliveryRepository;

  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {

  }
  @AfterEach
  public void tearDown() {

    User user = userRepository.findByName("marchingfood");
    user.setPassword("marchingfood");
    userRepository.save(user);

    Delivery del = deliveryRepository.findDeliveryById(11L);
    del.setStage(Delivery.Stage.REQUESTED);
    deliveryRepository.save(del);

    //driver.quit();
  }
  @Test
  public void mainCompanyIntegration(ChromeDriver driver) {
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://db_main:8080/login");
    driver.manage().window().setSize(new Dimension(1456, 876));
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("marchingfood");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("marchingfood");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).getText(), is("11"));
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(5) > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(5)")).click();
    driver.findElement(By.linkText("Profile")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("newPassword")).sendKeys("newpass");
    driver.findElement(By.id("password")).sendKeys("marchingfood");
    driver.findElement(By.cssSelector(".col-3 > .button")).click();

    driver.findElement(By.id("username")).sendKeys("marchingfood");
    driver.findElement(By.id("password")).sendKeys("newpass");
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("LogisticsMarshall")).click();
    driver.findElement(By.cssSelector("h2")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Welcome to Logistics Marshall"));
    driver.findElement(By.linkText("Dashboard")).click();
    {
      WebElement element = driver.findElement(By.linkText("Dashboard"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Log Out")).click();
  }
}
