package logisticsmarshall.tqs.ua.controllers;// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.web.server.LocalServerPort;

import java.util.*;


@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ExtendWith(SeleniumJupiter.class)
public class MainRegisterCompanyIT {

  @LocalServerPort
  int serverPort;

  String url;

  @BeforeEach
  public void setUp() {
    url = String.format("http://backendmain:%d/", serverPort);
  }

  @Test
  public void mainRegisterCompanyIntegration(ChromeDriver driver) {
    String clientName = UUID.randomUUID().toString();
    String clientEmail = clientName+"@email.com";
    String clientPass = "randompass";

    driver.get(url + "login");
    driver.manage().window().setSize(new Dimension(1456, 876));
    {
      List<WebElement> elements = driver.findElements(By.linkText("Log In"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Log In")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("span > a"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("span > a")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys(clientName);
    driver.findElement(By.name("email")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.name("email")).sendKeys(clientEmail);
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.name("password")).sendKeys(clientPass);
    driver.findElement(By.name("role")).click();
    driver.findElement(By.cssSelector("#div1 > h3")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#div1 > h3"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("deliveryType")).click();
    driver.findElement(By.id("deliveryType")).sendKeys("food");
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("address")).sendKeys("Street close to the church");
    driver.findElement(By.id("phoneNumber")).click();
    driver.findElement(By.id("phoneNumber")).sendKeys("9122222222");
    driver.findElement(By.cssSelector(".alt")).click();
    driver.findElement(By.id("username")).sendKeys(clientName);
    driver.findElement(By.id("password")).sendKeys(clientPass);
    driver.findElement(By.id("login-submit")).click();
    driver.findElement(By.linkText("Log Out")).click();
  }
}
