version: "3.8"
services:
  backend:
    build: .
    #image: dioben/tqs-client-server:dev
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -h localhost -d postgres -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5433
    command: -p 5433
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
networks:
  default:
    external: true
    name: global_network

