version: "3.8"
services:
  backend:
    image: dioben/tqs-client-server:dev
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -h localhost -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./client-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
